### ISSUE TITLE
Number of clients running different than clients started

### ISSUE THREAD

**Issue by jadali17** [scaleoutsystems/fedn#104]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
It seems that when i start a federation round. The combiner doesn't always request the same amount of clients running. I am not sure if this is intended. In my scenario started 5 clients, when federation starts:
combiner_1   | COMBINER(combiner):0 waiting for 4 clients to get started, currently: 4 
It seems to happen at random, sometimes it would even wait for 3 clients to get started and currently indicates : 2 only in the exact same scenario
**Environment:**
 - OS: [windows]
 - Version: [10]
 - Browser [mozilla]
 - Version [83.0]

**Reproduction Steps**
Follow the documentation to run the mnist test word for word.

**Expected behavior**
If i start 5 clients,  all 5 clients should be used for the federation process

**Contact Details**
jadalidaoud@gmail.com

**Comment by morganekmefjord** [comment]
I think this is documented but lets revisit that.

It is a feature by design that a combiner can choose the number of clients it wants from the "pool" of clients that are connected.
The minimum number of client can be forced with setting required clients when starting the combiner. Check the cli for that argument.

The current assignment of FedAvgCombiner will select at random between the number required and the number connected.
