### ISSUE TITLE
Uploading new seed models unavailable

### ISSUE THREAD

**Issue by jadali17** [scaleoutsystems/fedn#106]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
There doesn't seem to be a consice way of uploading a new model when training on new examples. For example once model of data-center is uploaded, i cannot reupload any other model even when pushing the mnist model to minio. The command line would still display that the combiner is attempting to pass on the data-center model. Not sure if i am missing something or it is a bug.

**Environment:**
 
- OS: [windows]
- Version: [10]
- Browser [mozilla]
- Version [83.0]
- Tensorflow 2.3.1

**Reproduction Steps**
1. Run first example as data-center
2. Upload the data-center seed model
3. Try to run mnist example
4. No option to upload model on https://localhost:8090/seed
5. Try to upload file to minio
6. Try to run mnist example again

**Expected behavior**
Running new example should use appropriate models that are available

**Screenshots**

![image](https://user-images.githubusercontent.com/32588749/101408438-b1178000-38dc-11eb-8935-df0ada5f63cc.png)

**Contact Details**
jadalidaoud@gmail.com

**Comment by morganekmefjord** [comment]
It is by design that no new model is allowed to be uploaded once a network has started working on a problem. The consequences of being able to abort the model trail and injecting a new model of other origin or training is to severe. There are however ideas on how to be able to work on multiple models within the same alliance. And there will be features coming that would enable that behaviour, but not in this version of the product.
